# All tests for the CommunicationModule

load("//test:unity_helpers.bzl", "generate_a_unity_test_for_every_file")

generate_a_unity_test_for_every_file(
    glob(["*_Test.c"])
)

test_suite(
  name = "ALL"
  )
