cc_test(
        name = "Mutex-test",
        srcs = ["Mutex_Test.c"],
        copts = ["-Iexternal_deps/Unity/src"],
        deps = [
                "//external_deps/Unity/src:unity",
                "//lib:CommunicationModule",
                ],
        size = "small"
        )
