
#ifndef COMMUNICATIONMODULE_EXCEPTION_H
#define COMMUNICATIONMODULE_EXCEPTION_H

enum ExceptionValues {
  SPI_BUSY_EXCEPTION = 0x01,
  NETWORK_HARDWARE_IS_BUSY_EXCEPTION = 0x02,
};

#endif //COMMUNICATIONMODULE_EXCEPTION_H
